config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :proposals do
    patch 'approve', to: 'proposals#approve'
    resources :approval_flows, only: [:create, :new] do
      resources :steps, only: [:create, :edit, :new, :update] do
        resources :comments, only: [:create, :new]
      end
    end
  end
  resources :approval_flows, only: :show
  resources :steps, only: [:destroy] do
    patch 'approve', to: 'steps#approve'
    patch 'reject', to: 'steps#reject'
    patch 'request_change', to: 'steps#request_change'
    patch 'new_review', to: 'steps#new_review'
    patch 'start', to: 'steps#start'
  end
  get 'dashboard', to: 'pages#dashboard'
  get '/user' => "pages#dashboard", :as => :user_root
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/approval_flow.rb
class ApprovalFlow < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: :user_id, primary_key: :id
  belongs_to :proposal
  has_many :steps
  has_many :comments, through: :steps # @approval_flow.comment
  validates :name, presence: true
end

app/controllers/approval_flows_controller.rb
class ApprovalFlowsController < ApplicationController

  def new
    @approval_flow = ApprovalFlow.new
    @proposal = Proposal.find(params[:proposal_id])
  end

  def create
    @approval_flow = ApprovalFlow.new(approval_flow_params)
    @approval_flow.creator = current_user
    @approval_flow.proposal = Proposal.find(params[:proposal_id])
    if @approval_flow.save
      redirect_to proposal_path(@approval_flow.proposal), notice: "Your approval flow has been created"
    else
      # not sure about this else
      render "approval_flow/new"
    end
  end

  def show
    @approval_flow = ApprovalFlow.find(params[:id])
    @proposal = @approval_flow.proposal
    # @step = Step.new
    @ordered_steps = @approval_flow.steps.order('created_at asc') if @approval_flow.steps
    @step = Step.new
  end

  def destroy
    @step = Step.find(params[:id])
    @step.destroy
    redirect_to approval_flow_path(@step.approval_flow), notice: "The step has been eliminated"
  end

  def approve
    @step = Step.find(params[:id])
    @step.status = "approved"
  end

  def reject
    @step = Step.find(params[:id])
    @step.status = "rejected"
  end

  def change_request
    @step = Step.find(params[:id])
    @step.status = "change request"
  end

  private

  def approval_flow_params
    params.require(:approval_flow).permit(:name, :description)
  end

end

app/views/approval_flows/new.html.erb
<%# this could be a modal in the proposal show page with a button that shows if @proposal.approval_flow is nil %>
<p> Approval Flow for <%= @proposal.title %></p>
<%= simple_form_for [@proposal, @approval_flow] do |f| %>
        <%= f.input :name, label: "Approval Flow Name" %>
        <%= f.input :description, label: 'Description of the approval flow' %>
        <%= f.submit "Submit ", class: "btn btn-primary" %>
<%  end %>

app/views/approval_flows/show.html.erb
<div class="container d-flex approval-flow-main-box" style="padding: 20px">
  <div class="container d-flex flex-column">
      <h1><%= @approval_flow.name.capitalize %></h1>
      <h2>Proposal</h2>
      <p><%= link_to @approval_flow.proposal.title, proposal_path(@approval_flow.proposal)%></p>
      <h2>Description </h2>
      <p><%= @approval_flow.description%></p>
      <%= link_to "Back to Proposal", proposal_path(@proposal), class: "btn btn-flat-white ", style: "margin:auto; margin-bottom: 0;" %>
  </div>
  <div class="container d-flex flex-column justify-content-between">
    <div class="container d-flex">
        <i class="fas fa-history blue" style="font-size: 30px; padding-top: 9px; padding-right: 8px;"></i>
        <h1 class="blue" style="font-weight: normal;">Approvers</h1>
    </div>
    <div class="container d-flex flex-column">
        <% @ordered_steps.each_with_index do |step, i| %>
          <% case step.status %>
            <% when 'approved' %>
              <% color = "green" %>
            <% when 'rejected' %>
              <% color = "red" %>
            <% when 'created' %>
              <% color = "blue" %>
            <% when 'change request' %>
              <% color = "yellow" %>
            <% when 'in review' %>
              <% color = "yellow" %>
            <% when 'new review' %>
              <% color = "yellow" %>
          <% end %>
          <div class="container d-flex light-blue step-card justify-content-between" style="margin-bottom: 5px">
              <div><i class="fas fa-square blue <%=color%>"></i></div>
              <div style="margin-right: auto; padding-left: 16px; width: 30%;"><%= i + 1 %>. <%= step.approver.first_name %> <%= step.approver.last_name %>  </div>
              <div style="margin-right: auto"><%= step.status.capitalize %></div>
          </div>
        <%end%>
    </div>
    <%= link_to "Add Approver", new_proposal_approval_flow_step_path(@proposal, @approval_flow), data: { bs_toggle: "modal", bs_target:"#exampleModalStep" }, class: "btn btn-flat-white ", style: "width: fit-content;margin-left: auto;margin-right: auto;" %>
  </div>
</div>




<div class="modal fade" id="exampleModalStep" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add approver to <%= @approval_flow.proposal.title %>:</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <%= simple_form_for [@approval_flow.proposal, @approval_flow, @step] do |f| %>
              <%= f.input :approver, label: "Approver email" %> <%# We need to give the possibilty to chose among created users? or just input the email? %>
              <%= f.submit "Add Approver", class: "btn btn-primary" %>
          <%  end %>
      </div>
    </div>
  </div>
</div>