config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :proposals do
    patch 'approve', to: 'proposals#approve'
    resources :approval_flows, only: [:create, :new] do
      resources :steps, only: [:create, :edit, :new, :update] do
        resources :comments, only: [:create, :new]
      end
    end
  end
  resources :approval_flows, only: :show
  resources :steps, only: [:destroy] do
    patch 'approve', to: 'steps#approve'
    patch 'reject', to: 'steps#reject'
    patch 'request_change', to: 'steps#request_change'
    patch 'new_review', to: 'steps#new_review'
    patch 'start', to: 'steps#start'
  end
  get 'dashboard', to: 'pages#dashboard'
  get '/user' => "pages#dashboard", :as => :user_root
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner-home.html.erb
<div style="background-color: #0E1B4C">
  <div class="banner-home container d-flex flex-column justify-content-center align-items-baseline" style="">
      <%= image_tag "logo-decide-it-long.svg", class: "logo-home-banner"%>
      <h1 id="home-banner-header">Prepare your <span class="italic">projects for success.</span></h2>
      <h2 id="home-banner-header">Enhance <span class="italic">decision making.</span></h2>
      <%# <p id="p-home-banner">A new way of working. Stay agile. Stay aligned.</p> %>
        <% if user_signed_in?  %>
          <%= link_to "Try Decide.it", dashboard_path, class: "btn-flat-white", id: "btn-home" %>
        <% else  %>
          <%= link_to "Try Decide.it", new_user_registration_path, class: " btn-flat-white", id: "btn-home" %>
        <% end  %>
  </div>
</div>

app/views/shared/_card-approval.html.erb
<% @user.steps.each do |step| %>
  <%#= link_to proposal_path(proposal) %>
  <% if step.status == "in review" || step.status == "new review" %>
    <div class="card-proposal mb-4">
        <div class="card-proposal-info-top">
          <h2><%= link_to step.approval_flow.proposal.title, proposal_path(step.approval_flow.proposal) %></h2>
          <p><%= step.approval_flow.proposal.description%></p>
        </div>

        <div class="card-proposal-info-bottom">
          <p class="p-2 bd-highlight"><i class="fas fa-user-astronaut p-2"></i><%= step.approval_flow.proposal.creator.email %></p>
          <p class="p-2 bd-highlight"><i class="far fa-calendar-alt p-2"></i> <%= step.approval_flow.proposal.created_at.strftime("%e %b %Y") %></p>
          <% link_to "Proposal Page", proposal_path(step.approval_flow.proposal) %>
        </div>
    </div>
    <% @counter_approvals += 1  %>
  <% end %>
<% end %>
<% if @counter_approvals == 0 %>
  <p>You don't have any pending approval requests</p>
<%end  %>

app/views/shared/_card-change.html.erb
<% @user.proposals.each do |proposal| %>
  <% proposal.steps.each do |step| %>
    <% if step.status == "change request"  %>
        <div class="card-proposal mb-4">
            <div class="card-proposal-info-top">
              <h2><%= link_to step.approval_flow.proposal.title, proposal_path(step.approval_flow.proposal) %></h2>
              <p><%= step.approval_flow.proposal.description%></p>
            </div>
            <div class="card-proposal-info-bottom">
              <p class="p-2 bd-highlight"><i class="fas fa-user-astronaut p-2"></i><%= step.approval_flow.proposal.creator.email %></p>
              <p class="p-2 bd-highlight"><i class="far fa-calendar-alt p-2"></i> <%= step.approval_flow.proposal.created_at.strftime("%e %b %Y") %></p>
              <% link_to "Proposal Page", proposal_path(step.approval_flow.proposal) %>
            </div>
        </div>
        <% @counter_change_requests += 1  %>
    <% end %>
  <% end %>
<% end %>
<% if @counter_change_requests == 0 %>
  <p>You don't have any pending change requests</p>
<%end  %>

app/views/shared/_card-proposal.html.erb
<div>
<div class="descriptive-items">
      <p style="width: 50%">Title</p>
      <%# <p style="width: 25%">Description</p> %>
      <p style="width: 20%">Creator</p>
      <p style="width: 15%">Creation Date</p>
      <p style="width: 15%">Status</p>
</div>
<% @proposals.each do |proposal| %>
  <%#= link_to proposal_path(proposal) %>
    <% case proposal.status %>
          <% when 'approved' %>
            <% color = "green" %>
          <% when 'rejected' %>
            <% color = "red" %>
          <% when 'initiated' %>
            <% color = "blue" %>
      <% end %>
    <div class="card-proposal mb-4" >
      <div class="card-proposal-info-top">
        <% if proposal.title.length > 40 %>
             <h4 style="width: 50%; margin: 0"><%= link_to "#{proposal.title.first(40)}...", proposal_path(proposal)%></h4>
        <% else %>
            <h4 style="width: 50%; margin: 0"><%= link_to proposal.title, proposal_path(proposal)%></h4>
        <% end %>
         <%# <% if proposal.title.length > 20 %>
             <%# <p style="width: 25%"><%= "#{proposal.description.first(20)}..."</p> %>
        <%# <% else %>
            <%# <p style="width: 25%"><%= proposal.description</p> %>
        <%# <% end %>
        <p class="bd-highlight" style="width: 20%; margin: 0"><%= proposal.creator.first_name %> <%= proposal.creator.last_name %></p>
        <p class="bd-highlight" style="width: 15%; margin: 0"> <%= proposal.created_at.strftime("%e %b %Y") %></p>
        <p class="bd-highlight" style="width: 15%; margin: 0"> <i class="fas fa-square blue <%=color%>"></i> <%= proposal.status.capitalize %></p>

        <% link_to "Proposal Page", proposal_path(proposal) %>
      </div>
      <%# <div class="card-proposal-info-bottom">
      </div> %>
    </div>
    <% @counter_proposals += 1  %>
<% end %>
<% if @counter_proposals == 0 %>
  <p>You haven't created any proposal yet.</p>
<%end  %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer-home.html.erb
<div class="footer">
    <div class="home-logo">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo-decide-it-short.svg" %>
      <% end %>
    </div>
  <div class="footer-links">
    <a href="#" class="m-3">FAQs</a>
    <a href="#" class="m-3">Terms & Conditions</a>
    <a href="#" class="m-3">Privacy Policy</a>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_home-banner.html.erb
<div style="background-color: #0E1B4C">
  <div class="banner-home container d-flex flex-column justify-content-center align-items-baseline" style="">
      <%= image_tag "logo-decide-it-long.svg", class: "logo-home-banner"%>
      <h1 id="h1-home-banner">Efficient <span class="italic">decision making</span>, prepare your projects for <span class="italic">success.</span></h1>
      <%# <p id="p-home-banner">A new way of working. Stay agile. Stay aligned.</p> %>
        <% if user_signed_in?  %>
          <%= link_to "Try Decide.it", dashboard_path, class: "btn-flat-blue", id: "btn-home" %>
        <% else  %>
          <%= link_to "Try Decide.it", new_user_session_path, class: " btn-flat-blue", id: "btn-home" %>
        <% end  %>
  </div>
</div>

app/views/shared/_home-cards.html.erb
<div class="container" id="personality">
  <h2 class="category-header pb-4"></h2>
  <div class="row justify-content-center" id="grid-gap">
    <div class="card-trip col">
        <img src="https://cdn.dribbble.com/users/1815631/screenshots/14598430/media/105f796bf7e3ecae0b5fc9f6eef63ee1.png?compress=1&resize=1200x900&vertical=top" />
        <div class="card-trip-infos odd d-flex flex-column">
            <h2>Agility</h2>
            <p>Create flexible approval flows</p>
        </div>
    </div>

    <div class="card-trip col">
        <img src="https://cdn.dribbble.com/users/646089/screenshots/14358445/media/e15e502a716d97c8cd6b882362d65b02.jpg?compress=1&resize=1200x900&vertical=top" />
        <div class="card-trip-infos even d-flex flex-column">
            <h2>High Visibility</h2>
            <p>Help decision making</p>
        </div>
    </div>

    <div class="card-trip col">
        <img src="https://cdn.dribbble.com/users/3470960/screenshots/15580151/media/db47e1ed7fdc096ae36bc42bff50564f.png?compress=1&resize=1200x900&vertical=top" />
        <div class="card-trip-infos odd d-flex flex-column">
            <h2>Consensus</h2>
            <p>Ensure internal alignment</p>
        </div>
    </div>

    <div class="card-trip col">
        <img src="https://cdn.dribbble.com/users/1286696/screenshots/4143669/media/fb300c3fa154653f60a7379dacd8d3df.png?compress=1&resize=800x600&vertical=top" />
        <div class="card-trip-infos even d-flex flex-column">
            <h2>Scalability</h2>
            <p>For fast growth organizations</p>
        </div>
    </div>

  </div>
</div>

app/views/shared/_navbar-home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon-home sticky-top justify-content-between">

  <div class="container d-flex justify-content-between p-0">

    <div class="container home-nav-items d-flex justify-content-between p-0">
      <%# <a class="navbar-brand-home" href="#">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
      </a> %>
      <%= link_to "#" do %>
        <i class="fi p-2"> Why decide.it?</i>
      <% end %>
      <%= link_to "#" do %>
        <i class="fi fi-rs-dollar p-2"> Pricing</i>
      <% end %>
      <%= link_to "#" do %>
        <i class="fi fi-rs-paper-plane p-2"> Contact</i>
      <% end %>
    </div>

    <div class="container d-flex justify-content-end flex-grow-1 p-0">
    </div>

    <div class="home-nav-items container d-flex justify-content-end align-items-center p-0">

      <%= link_to new_user_registration_path, class: "home-btn nav-link btn-squared-white p-2" do %>
        <i class="fi fi-rs-play"> Get Started</i>
      <% end %>

      <%= link_to new_user_session_path do %>
        <i class="fi fi-rs-sign-in p-2"> Sign in</i>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm fixed-left navbar-light navbar-lewagon sticky">
  <div class="container-fluid">
    <div class="home-logo">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo-decide-it-short.svg" %>
      <% end %>
    </div>


    <div class="collapse navbar-collapse">
      <ul class="navbar-nav me-auto" id="nav-user">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to proposals_path do %>
              <i class="fi fi-rs-list"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_proposal_path do %>
              <i class="fi fi-rs-plus"></i>
            <% end %>
          </li>
          <%# <li class="nav-item search-icon">
            <%= link_to "#" do %>
              <%# <i class="fas fa-search"></i> %>
            <%# <% end %>
          <%# </li> %>
          <li class="nav-item">
            <%= link_to dashboard_path do %>
              <i class="fi fi-rs-layout-fluid"></i>
            <% end %>
          </li>
          <li class="nav-item notifications">
            <%= link_to "#" do %>
              <i class="fi fi-rs-bell"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fi fi-rs-power"></i>
            <% end %>
          </li>
          <li class="nav-item">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar"%>
          <% else %>
            <%= image_tag "profile-image.jpg", class: "avatar"%>
          <% end %>

          </li>
        <% else %>
          <li class="log-out nav-item">
            <%= link_to new_user_session_path do %>
              <i class="fi fi-rs-sign-in"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_progress.html.erb
<h3>Progress:</h2>
<div>
    <ul>
      <% if @ordered_steps  %>
          <% @ordered_steps.each_with_index do |step, i| %>
            <li>
                <% if step.logs.length > 0 %>
                    <% step.logs.each do |log| %>
                      <p><span class="progress-dates-color"><%= log.user.first_name %> <%= log.user.last_name %></span> <%= log.updated_status %> on <span class="progress-dates-color"><%= log.created_at.strftime("%e %b %Y") %></span></p>
                    <% end  %>
                <% else %>
                      <span class="progress-dates-color"><%= step.approver.first_name %> <%= step.approver.last_name %></span> <%= step.status %> on <span class="progress-dates-color"><%= step.created_at.strftime("%e %b %Y")  %></span>
                <% end %>
            </li>
          <%end%>
      <% end  %>
    </ul>
</div>

app/views/shared/_table-proposal.html.erb
<table class="dashboard-table">
  <thead>
    <tr>
      <th>Title</th>
      <%# <th>Description</th> %>
      <th>Creator</th>
      <th>Activity</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @proposals.each do |proposal| %>
      <% case proposal.status %>
          <% when 'approved' %>
            <% color = "green" %>
          <% when 'rejected' %>
            <% color = "red" %>
          <% when 'initiated' %>
            <% color = "blue" %>
      <% end %>
      <tr>
        <td><%= link_to proposal.title, proposal_path(proposal), id: ""%></td>
        <%# <td> <p><%= proposal.description</p></td> %>
        <td><%= proposal.creator.first_name %> <%=proposal.creator.last_name%></td>
        <td><%= proposal.created_at.strftime("%e %b %Y") %></td>
        <td><i class="fas fa-square blue <%=color%>"></i> <%= proposal.status %></td>
      </tr>
    <% end %>
     <% @counter_proposals += 1  %>
  <% if @counter_proposals == 0 %>
  <p class="display-message">You haven't created any proposal yet</p>
  <%end  %>
  </tbody>
</table>

app/views/shared/_table-tasks.html.erb
<table class="dashboard-table">
    <tbody>
    <thead>
      <tr>
        <th>Title</th>
        <%# <th>Description</th> %>
        <th>Creator</th>
        <th>Activity</th>
        <th>Task</th>
      </tr>
    </thead>
    <% @user.steps.each do |step| %>
          <% case step.status %>
          <% when 'approved' %>
            <% color = "green" %>
          <% when 'rejected' %>
            <% color = "red" %>
          <% when 'initiated' %>
            <% color = "blue" %>
          <% when "in review" %>
            <% color = "yellow" %>
          <% when "new review" %>
            <% color = "yellow" %>
            <% when 'change request' %>
              <% color = "yellow" %>
          <% end %>
        <% if step.status == "in review" || step.status == "new review" %>
            <tr>
              <td><%= link_to step.approval_flow.proposal.title, proposal_path(step.approval_flow.proposal)%></td>
              <%# <td><%= step.approval_flow.proposal.description</td> %>
              <td><%= step.approval_flow.proposal.creator.first_name %> <%=step.approval_flow.proposal.creator.last_name %></td>
              <td><%= step.approval_flow.proposal.created_at.strftime("%e %b %Y") %></td>
              <td><i class="fas fa-square blue <%=color%>"></i>  <%= step.status.capitalize %></td>
            </tr>
            <% @counter_tasks += 1 %>
        <% end %>
      <% end %>
  <% @user.proposals.each do |proposal| %>
    <% proposal.steps.each do |step| %>
      <% if step.status == "change request"  %>
             <% case step.status %>
                <% when 'change request' %>
                  <% color = "yellow" %>
              <% end %>
            <tr>
              <td><%= link_to step.approval_flow.proposal.title, proposal_path(step.approval_flow.proposal) %></td>
              <%# <td><p><%= step.approval_flow.proposal.description</p></td> %>
             <td><%= step.approval_flow.proposal.creator.first_name %> <%=step.approval_flow.proposal.creator.last_name%></td>
              <td><%= step.approval_flow.proposal.created_at.strftime("%e %b %Y") %></td>
               <td><i class="fas fa-square blue <%=color%>"></i> <%= step.status.capitalize %></td>
            </tr>
        <% @counter_tasks += 1  %>
    <% end %>
  <% end %>
<% end %>
    </tbody>
  </table>
<% if @counter_tasks == 0 %>
  <p class= "display-message">You don't have any tasks</p>
<%end  %>

app/views/shared/_testimonials.html.erb
<div class="bg-testimonials">
  <div class="banner-testimonial container d-flex ">

    <div class="testimonial-container d-flex">
      <div class="client-text-container d-flex flex-column justify-content-between">
        <%= image_tag "lewagon.png", class: "image-card-home"%>
        <div class="header-text  mt-3">
          <h4>“New employees can look at the Creative Requests board, and immediately understand what the entire marketing team is working on without having to ask.”</h4>
          <p class="mt-4">Emilia Ivaylova | Operations Manager | Le Wagon Madrid</p>
        </div class=" mt-5">
        <h4><%= link_to "Meet our customers", "#", class: "testimonial-btn" %></h4>
      </div>
    </div>

    <div class="client-image-container">
      <div class="bg-square">
        <%= image_tag "emi-at-le-wagon.jpg", class: "image-card-home"%>
      </div>
    </div>

  </div>
</div>