config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :proposals do
    patch 'approve', to: 'proposals#approve'
    resources :approval_flows, only: [:create, :new] do
      resources :steps, only: [:create, :edit, :new, :update] do
        resources :comments, only: [:create, :new]
      end
    end
  end
  resources :approval_flows, only: :show
  resources :steps, only: [:destroy] do
    patch 'approve', to: 'steps#approve'
    patch 'reject', to: 'steps#reject'
    patch 'request_change', to: 'steps#request_change'
    patch 'new_review', to: 'steps#new_review'
    patch 'start', to: 'steps#start'
  end
  get 'dashboard', to: 'pages#dashboard'
  get '/user' => "pages#dashboard", :as => :user_root
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: :user_id, primary_key: :id
  has_one :approval_flow
  has_many :steps, through: :approval_flow
  validates :title, presence: true
  validates :description, presence: true
  validates :status, presence: true, inclusion: { in: ["initiated", "in review", "approved", "rejected"] }
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  def index
    @proposals = Proposal.all
    @counter_proposals = 0
  end

  def new
    @proposal = Proposal.new
  end

  def create
    @proposal = Proposal.new(proposal_params)
    @proposal.creator = current_user
    if @proposal.save
      redirect_to proposal_path(@proposal.id), notice: 'Proposal was successfully created.'
    else
      render "proposals/new"
    end
  end

  def update
    @proposal = Proposal.find(params[:id])
    if @proposal.update(proposal_params)
      redirect_to proposal_path(@proposal.id), notice: 'Proposal was successfully updated.'
    else
      render "proposals/edit"
    end
  end

  def edit
    @proposal = Proposal.find(params[:id])
  end

  def show
    @proposal = Proposal.find(params[:id])
    # @proposal = Proposal.new
    # comprobar 1. si el current user es approver de algun step de la proposal
    # comprobar 2. si ese step el status es igual a "in review"
    # si es asi --> mostrar los botones de aprobacion/rechazo/change_request + edit de la proposal
    @action_step = in_review_step_current_user(@proposal)
    @ordered_steps = @proposal.approval_flow.steps.order('created_at asc') if @proposal.approval_flow
    @comment = Comment.new
    @user = current_user
    @step = Step.new
  end

  def in_review_step_current_user(proposal)
    action_step = nil
    proposal.steps.each do |step|
      if step.approver == current_user && (step.status == "in review" || step.status == "new review")
        action_step = step
      end
    end
    action_step
  end

  def archive
    @proposal.archive = true
  end

  def reject
    @proposal = Proposal.find(params[:id])
    @proposal.status = "rejected"
  end

  def approve
    @proposal = Proposal.find(params[:proposal_id])
    @proposal.status = "approved"
    if @proposal.save
      redirect_to proposal_path(@proposal.id)
    end
  end

  private

  def proposal_params
    params.require(:proposal).permit(:title, :description, :status, :scope, :budget, :due_date)
  end
end

app/views/proposals/_form.html.erb
<div data-controller='preview-file'>

  <%= simple_form_for [@proposal] do |f| %>
  <div class="form-inputs">
      <%= f.input :title, label: "Proposal Title", placeholder: 'E.g. Veggie options in lunch menu' %>
      <%= f.input :description, label: "Proposal Description", placeholder: 'E.g. I am vegetarian and it would be very nice to...' %>
      <%# <%= f.input :status, :collection => %w[initiated in_review approved rejected], :prompt => "Select the status"%>
      <%= f.input :scope, placeholder: 'E.g. Madrid office (optional)'%>
      <%= f.input :budget,  placeholder: 'E.g $10 (optional)' %>
      <%= f.input :due_date, as: :string, input_html: {class: "datepicker"} , label: "Due Date", placeholder: 'E.g. 20/4/2022' %>
      <div data-preview-file-target="preview" class= "image-upload"></div>
      <%# <%= f.input :attached_docs, label: "Attached Files", as: :file, label_html: {data: {preview_file_target: "label"} }, input_html: { multiple: true, data: { action: "change->preview-file#show", preview_file_target: "input" } } %>
  </div>

    <div class="form-actions text-center">
      <%=f.submit "Submit ", class: "btn btn-primary"%>
    </div>
  <% end %>

</div>

app/views/proposals/edit.html.erb
<div class="container pt-5 mb-5" >
  <h2 class="all-forms" style="text-align:center">Create a new proposal</h2>
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3">
        <%= render 'form', proposal: @proposal  %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Show', @proposal %>

app/views/proposals/index.html.erb
<div class="all-proposals-container">
  <div class="all-proposals-header mb-4">
    <h1>All Proposals</h1>
    <%= link_to "Create new proposal", new_proposal_path, class: "btn btn-flat-white"  %>
  </div>

  <div class="proposal-cards-container" style="background: #F2FBFF; padding: 20px;">
    <%= render "shared/card-proposal" %>
  </div>

</div>

app/views/proposals/new.html.erb
<div class="container pt-5 mb-5" >
  <h2 class="all-forms" style="text-align:center">Create a new proposal</h2>
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3">
        <%= render 'form', proposal: @proposal  %>
      </div>
    </div>
  </div>
</div>

app/views/proposals/show.html.erb
<div class="container-show p-5">
  <div class="proposal-progress-container d-flex justify-content-between pr-5 pt-5 pl-5">

    <div class="proposal-section mr-3 col-5">
      <div class="proposal-box mr-2">
        <div class="titles">
          <h2><%= @proposal.title %>
            <span> <%= link_to edit_proposal_path(@proposal), id: "edit-icon" do%>
            <i class="fi fi-rs-edit"></i>
            <% end %>
            </span>
          </h2>

        </div>
        <div class="proposal-description-details mt-5">
          <h4>Description</h4>
          <p><%= @proposal.description %></p>
          <div class="proposal-details d-flex justify-content-between mt-4">
            <div class="proposal-status m-2">
              <h4>Status</h4>
              <p><%= @proposal.status.capitalize  %></p>
            </div>
            <div class="proposal-budget  m-2">
              <h4>Budget</h4>
              <% if @proposal.budget %>
                <p><%=@proposal.budget.round %>€</p>
              <% else %>
                <p>-</p>
              <% end %>
            </div>
            <div class="proposal-due-date  m-2">
              <h4>Due date </h4>
              <p><%=@proposal.due_date %></p>
            </div>
            <div class="proposal-scope  m-2">
            <h4>Scope</h4>
            <% if @proposal.scope %>
              <p><%=@proposal.scope.capitalize %></p>
            <% else %>
              <p>-</p>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-1">
    </div>
    <div class="progress-section ml-3 col-6">
      <div class="progress-steps blue-box p-3 mb-5">
        <h3><i class="fi fi-rs-time-past pb-3" style="font-size: 16px" ></i> Progress:</h3>
        <div class="step-list">
          <div class="step-container">
            <p> <i class="fas fa-square green" id="status-color-icon"> </i><span class="blue-p" > 1. </span> Created by <span class="blue-p"> <%= @proposal.creator.first_name %> <%= @proposal.creator.last_name[0] %>. </span> on <span class="blue-p"><%= @proposal.created_at.strftime("%e %b %Y") %></span></p>
          </div>
          <% if @ordered_steps %>
            <% @ordered_steps.each_with_index do |step, i| %>
              <% case step.status %>
                <% when 'approved' %>
                  <% color = "green" %>
                <% when 'rejected' %>
                  <% color = "red" %>
                <% when 'created' %>
                  <% color = "blue" %>
                <% when 'change request' %>
                  <% color = "yellow" %>
                <% when 'in review' %>
                  <% color = "yellow" %>
                <% when 'new review' %>
                  <% color = "yellow" %>
              <% end %>
            <div class="step-container">
              <p> <i class="fas fa-square <%=color%>"  id="status-color-icon"></i> <span class="blue-p"><%= i + 2 %>.</span>  Approver <span class="blue-p"><%= step.approver.first_name %> <%= step.approver.last_name[0] %>. </span>  Status  <span class="blue-p"><%= step.status %></span><span class="blue-p" > on <%= step.updated_at.strftime("%e %b %Y") %></span></p>
                <%# <% if step.logs %>
                  <%# <% step.logs.each do |log| %>
                  <%# on <span class="blue-p"><%= log.created_at.strftime("%e %b %Y") </span></p>%>
                  <%# <% end %>
                <%# <% end %>
              <%# </p> %>
            </div>
            <% end %>
          <% end %>

          <% if @proposal.approval_flow %>
            <div class="with-created-approval mt-4">
              <h4>Approval Flow: <%= link_to @proposal.approval_flow.name, approval_flow_path(@proposal.approval_flow), class: ""%></h4>
            </div>
          <% end %>
        </div>
      </div>
      <div class="approval-flow-actions d-flex align-items-center justify-content-between flex-wrap">
      <% if (@proposal.approval_flow) && (@proposal.approval_flow.steps.first) && (@ordered_steps.first.status == "created") && (@proposal.creator == current_user) %>
        <div class="approval-flow-start">
            <%= link_to "Start Approval Flow", step_start_path(@ordered_steps.first), method: "patch", class: "btn-flat-blue mb-3", style: " border: 3px solid $blue;", id: "start-btn"%>
      <% end %>
      </div>
      <div class="approval-flow-if-created" style="display: flex; flex-wrap: wrap; justify-content: space-between;">
        <% if @proposal.approval_flow.nil? && @proposal.creator == current_user %>
              <%= link_to  "Add Approvers", new_proposal_approval_flow_path(@proposal), class: "btn-flat-white", style: "width: fit-content;" %>
        <% end %>
        <% if (@proposal.approval_flow) && (@proposal.status == "initiated" || @proposal.status == "in review") %>
              <%= link_to "Add approvers", "#",data: { bs_toggle: "modal", bs_target:"#exampleModalStep" }, class: "btn-flat-white col-2", style: "width: fit-content;" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModalStep" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add approver to <%= @proposal.title%>:</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% if @proposal.approval_flow %>
          <%= simple_form_for [@proposal, @proposal.approval_flow, @step] do |f| %>
              <%= f.input :approver, label: "Approver email", collection: User.all.map { |user| user.email } %>
              <%= f.submit "Add Approver", class: "btn btn-primary" %>
          <%  end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

  <div class="buttons-and-comments row mt-3">
    <% if @action_step  %>
    <div class="actions-section">
        <h2 class="action-header mt-5 mb-5">What do you want to do?</h2>
        <div class="buttons-approve mb-5">
          <%= link_to "Approve", step_approve_path(@action_step), method: "patch", data: { bs_toggle: "modal", bs_target:"#exampleModal" }, class: "btn-green-approve" %>
          <%= link_to "Request Change", step_request_change_path(@action_step), method: "patch", data: { bs_toggle: "modal", bs_target:"#exampleModal" }, class: "btn-yellow-change" %>
          <%= link_to "Reject", step_reject_path(@action_step), method: "patch", data: { bs_toggle: "modal", bs_target:"#exampleModal" }, class: "btn-orange-reject" %>
        </div>
      <% end  %>
      <% if @proposal.creator == current_user && (@proposal.steps.count {|step| step.status == "change request"} >= 1) %>
        <div class="actions-section p-4 d-flex flex-column" style="align-items: center; justify-content: center;">
        <h2 class="action-header mt-5 mb-5">What do you want to do?</h2>
            <%= link_to "Submit changes", step_new_review_path(@proposal.steps.find {|step| step.status == "change request"}), method: "patch", data: { bs_toggle: "modal", bs_target:"#exampleModal" }, class: "buttons-approve btn-green-approve", style: "width: fit-content; padding: 8px 22px; font-size: 18px" %>
        </div>
      <% end  %>

      <%# --- modal --- %>
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add comment to action:</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <% if (@proposal.approval_flow) && (@proposal.approval_flow.steps.first)  %>
                  <%= simple_form_for [@proposal, @proposal.approval_flow, @proposal.approval_flow.steps.first, @comment] do |f| %>
                        <%= f.input :content, label: "Your comment" %>
                        <%= f.submit "Post", class: "btn btn-primary" %>
                  <%end%>
                <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

    <div class="approved-section">
      <% if @proposal.status == "approved"  %>
        <div class="end-message-approval-section d-flex flex-column justify-content-start align-items-center p-5 mt-3">
            <h3> 🎉 Congratulations! The proposal is approved! 🎉 </h3>
        </div>
      <%end %>
      <% if @proposal.status == "rejected"  %>
        <div class="end-message-approval-section d-flex flex-column justify-content-start align-items-center p-5 mt-3">
            <h3> 🚫 The proposal has been rejected. 🚫 </h3>
        </div>
      <%end %>


      <% if @proposal.steps.first %>
        <% if (@proposal.steps.order('created_at asc').last.approver == current_user) && (@proposal.steps.order('created_at asc').last.status == "approved") && (@proposal.status != "approved") %>
            <div class="final-approval-section d-flex flex-column justify-content-start align-items-center pl-5 pr-5 mt-3">
              <%# <div class="final-approval-text mr-5"> %>
                <h4 class="final-approval-header mt-5 mb-3 p-2" style="text-align:center;color: #576BB1;font-family: 'Trispace', sans-serif;" >You are the final approver of this proposal. <br>🙌<br>  Please add a new approver if necessary or confirm the approval.</h4>
                <%# <h5>Please add a new approver if necessary or confirm the approval.</h5> %>
                <%= link_to "Confirm final approval", proposal_approve_path(@proposal), method: "patch", class: "btn-flat-white m-5", style: "background: #576BB1;color: white;" %>
              <%# </div> %>
            </div>
        <% end  %>
      <% end  %>
    </div>

  <% if @proposal.steps.first  %>
    <div class="comments-section">
      <div class="add-comment-box mt-3">
        <h3 class="mb-1">+ Add a comment</h3>
        <%= simple_form_for [@proposal, @proposal.approval_flow, @proposal.approval_flow.steps.first, @comment] do |f| %>
              <div class="comment-form d-flex justify-content-start ">
                <%= f.input :content, label: "", wrapper_html: { class: 'd-flex flex-row-reverse' }, label_html: { style: "display: none" } %>
                <%= f.submit "post", class: "btn-flat-blue ml-2", style: "margin-left: 20px !important;" %>
              </div>
        <% end %>
    </div>
  <% end %>

  <% if @proposal.steps.first  %>
    <div class="all-comments-box mt-3 p-5">
      <h3 class="mb-1">All Comments:</h3>
  <% end  %>
          <% if @ordered_steps %>
            <% @ordered_steps.each do |step| %>
            <% if step.comments %>
              <% step.comments.each do |comment| %>
                <div class="comment-item mb-3 p-2">
                  <h5>Posted by <%= comment.user.first_name %> <%#= comment.user.last_name %> on <%= comment.created_at.strftime("%e %b %Y")  %></h5>
                  <p><%= comment.content %></p>
                </div>
            <% end %>
          <% end %>
        <%end%>
      <%end%>
      </div>
    </div>
  </div>
</div>